# .streamlit/secrets.toml

[passwords]
# Follow the rule: username = "password"
Matt = "Lewis"
Tom = "Gosper"
Suraj = "Shrestha"
Raelyn = "Sangil"


[COMPANY 1]
Company 1 = "password 1"

[COMPANY 2]
Company 2 = "password 2"

[COMPANY 3]
Company 3 = "password 3"

[COMPANY 4]
Company 4 = "password 4"

[COMPANY 5]
Company 5 = "password 5"

[COMPANY 6]
Company 6 = "password 6"

[COMPANY 7]
Company 7 = "password 7"

[COMPANY 8]
Company 8 = "password 8"

[COMPANY 9]
Company 9 = "password 9"

[COMPANY 10]
Company 10 = "password 10"
