# .streamlit/secrets.toml

[passwords]
# Follow the rule: username = "password"
Matt = "Lewis"
Tom = "Gosper"
Suraj = "Shrestha"
Raelyn = "Sangil"


[SELLER]
Seller = "password"

[BUYER]
Buyer = "password"

["COMPANY 1"]
Company_One = "password 1"

["COMPANY 2"]
Company_Two = "password 2"

["COMPANY 3"]
Company_Three = "password 3"

["COMPANY 4"]
Company_Four = "password 4"

["COMPANY 5"]
Company_Five = "password 5"

["COMPANY 6"]
Company_Six = "password 6"

["COMPANY 7"]
Company_Seven = "password 7"

["COMPANY_8"]
Company_Eight = "password 8"

["COMPANY_9"]
Company_Nine = "password 9"

["COMPANY_10"]
Company_Ten = "password 10"